import eslint from "@eslint/js";
import tseslint from "typescript-eslint";
import prettier from "eslint-config-prettier";

export default tseslint.config(
  eslint.configs.recommended,
  ...tseslint.configs.strictTypeChecked,
  ...tseslint.configs.stylisticTypeChecked,
  prettier,
  {
    languageOptions: {
      parserOptions: {
        projectService: true,
        tsconfigRootDir: import.meta.dirname,
      },
    },
  },
  {
    rules: {
      // Security
      "no-eval": "error",
      "no-implied-eval": "error",
      "no-new-func": "error",

      // Quality
      // `ignoreRestSiblings` covers the deliberate `const { key: _v, ...rest }`
      // omit pattern: the renamed sibling exists ONLY to be excluded from rest.
      // Any other unused variable still errors (ADR-QUALITY-01).
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", ignoreRestSiblings: true },
      ],
      "@typescript-eslint/restrict-template-expressions": ["error", { allowNumber: true }],

      // Allow explicit any in test files
      "@typescript-eslint/no-explicit-any": "warn",
    },
  },
  {
    // Generated output only. Patterns are recursive on purpose: flat-config
    // ignores resolve against the config file's directory, so a bare `.next/`
    // would miss `apps/web/.next/` and let build artifacts reach the gate.
    ignores: [
      "**/node_modules/",
      "**/dist/",
      "**/.next/",
      "**/.turbo/",
      "**/coverage/",
      "**/build/",
      // Regenerated by `next dev`/`next build` on every run — editing it would
      // be overwritten, and its triple-slash reference is Next's own contract.
      "**/next-env.d.ts",
      "eslint.config.mjs",
    ],
  },
);